"""add_tickflow_and_lof_support

Revision ID: c798a3607fe2
Revises: e8b2c4d6f901
Create Date: 2026-05-27 15:50:45.503301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c798a3607fe2'
down_revision: Union[str, Sequence[str], None] = 'e8b2c4d6f901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT OR IGNORE INTO sys_datasource (source_id, is_enable)
        VALUES ('tickflow', 1)
        """
    )
    op.execute(
        """
        INSERT OR IGNORE INTO sys_data_router (asset_type, interface, source_id, priority)
        VALUES 
        ('LOF', 'daily_bar', 'lixinren', 1),
        ('LOF', 'net_value', 'lixinren', 1),
        ('FUND', 'daily_bar', 'lixinren', 1),
        ('FUND', 'net_value', 'lixinren', 1)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM sys_data_router WHERE asset_type IN ('LOF', 'FUND')")
    op.execute("DELETE FROM sys_datasource WHERE source_id = 'tickflow'")
    # ### end Alembic commands ###
